export enum RoutesEnum {
  signAndSend = '/sign-and-send',
  send = '/send',
  myAssets = '/my-assets',
  assetSelection = '/selection',
  transactions = '/transactions',
  add = '/add',
  discover = '/discover',
  myPlace = '/my-place',
  build = '/build',
  contribute = '/contribute',
  signup = '/signup',
  root = '/',
  login = '/login',
}
